sudo: false
language: node_js
node_js:
  - "10"
install: npm install
script:
  - npm test
  - gulp build
cache:
  directories:
    - node_modules
# Deploy using awscli to enable pruning of removed files
# before_deploy: pip install --user awscli && echo $(ls)
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: joincircles.net-content
    skip_cleanup: true
    local_dir: build
    acl: public_read
    on:
      branch: master
    region: eu-central-1
    cache_control: "max-age=21600"
# after_deploy:
#   - >
#     if ! [ "$BEFORE_DEPLOY_RUN" ]; then
#       export BEFORE_DEPLOY_RUN=1;
#       # Allow `awscli` to make requests to CloudFront.
#       aws configure set preview.cloudfront true
#       # Invalidate every object in the targeted distribution.
#       aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
#     fi

